### ISSUE TITLE
Line position when navigating between bookmarks

### ISSUE THREAD

**Issue by juancpgo** [chestozo/vscode-bookmarksng#1]
Not really an issue, but an observation regarding usability.

When I move to the next or previous bookmark, I feel the text cursor should get positioned at the top (first visible line), and not in the middle like it currently works.

The reason I would prefer the top is that I use bookmarks mainly to divide large files into chapters and move between those chapters easily. So when I jump between those chapters, I would like to see the bookmarked line sort of as the title, and the more visible lines below it, the better.

I suspect other people would feel the same way about this, I guess it depends on how people use bookmarking. When people want to bookmark lines for code that needs to be fixed, for example, then maybe this wouldn't be desirable, since they would prefer to see the context around it, below and above the bookmarked line. So I think if implemented, this should be an optional setting. Don't know if this is even possible to implement in VS Code though.

Thanks if you've read this.

**Comment by chestozo** [comment]
Added in 0.0.18 =)
