### ISSUE TITLE
 line highlight vanishes when switching to another file.

### ISSUE THREAD

**Issue by miwel04** [chestozo/vscode-bookmarksng#10]
The line highlight is lost when switching to another file.
I would like all highlights for all files visible at all times, since I use this to look at many different places with lots of similar lines.
Thanks for the extension, really helpful. 
Here is my env info (VSCodium):

Version: 1.55.1 (system setup)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-09T00:50:25.642Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by MdAman02** [comment]
Is this issue solved yet?

**Comment by miwel04** [comment]
I am not sure if solved here, but I found a fork from this project, from another author.
https://marketplace.visualstudio.com/items?itemName=balmacefa.linehighlightbookmarkvscode

The other author has solved the issue and I am using that other one. In that case I am closing this issue now.
