### ISSUE TITLE
Save bookmarks on exit?

### ISSUE THREAD

**Issue by cniggeler** [chestozo/vscode-bookmarksng#3]
Hi, would it be possible to save current bookmarks on exit and have them reload with the file the next time VS Code is started? Thanks!

**Comment by chestozo** [comment]
Hi, @cniggeler
This is how it should work right now.
What is your experience?

PS thank you for you support 💛

**Comment by chestozo** [comment]
I could reproduce one case when you add a bookmark and then quit VSCode right away - those are get lost.
Will fix this one!
Please let me know if you find any other cases

**Comment by cniggeler** [comment]
> I could reproduce one case when you add a bookmark and then quit VSCode right away - those are get lost.

I'm not sure what "right away" means. Is there some sort of time that has to elapse before the bookmarks "stick"?

When I end work for the day, I close Code and then shut down the computer, leaving the files I'm editing open (but saved) inside Code.

- If I set some bookmarks and then close Code, the bookmarks are gone.
- If I set some bookmarks, play with the file, save the file, then close Code, the bookmarks are also gone.

Am I supposed to do something to get them to reappear, other than reopening Code with the file already in the editor?

I am using VS Code version 1.46.1 (latest) with vscode-bookmark 0.19 (latest) on Windows 10 Pro version 2004 (latest). Thanks!

**Comment by chestozo** [comment]
> I'm not sure what "right away" means.
> Is there some sort of time that has to elapse before the bookmarks "stick"?

there should not be any right timing
so bookmarks should be saved straight away

let me fix the case the I've found and we see if it helps

**Comment by chestozo** [comment]
should be fixed in v0.20

**Comment by cniggeler** [comment]
This seems to have done it! Will keep you apprised if it recurs. Meanwhile, another issue just encountered, will open new report.
