### ISSUE TITLE
Does it really need 34MB of demo gifs?

### ISSUE THREAD

**Issue by rehierl** [chestozo/vscode-bookmarksng#6]
Don't get me wrong, the extension is great since it is reduced to what is needs to do.

However, the extension comes with a lot of dead weight - i.e. 34MB in demo gifs. That are only used to showcase the extension in the readme and on the marketplace. All those 411 people who installed the extension downloaded the demo files, although they will never get to use the storage space those gif images eat up.

You have contributed to (411*34MB=) 13.6 GB of needless network traffic.
I'm sure you can do better than that. :)

Please reduce the resolution and the length of these demo videos.

**Comment by chestozo** [comment]
super valid point @rehierl 
will place that gif to external cdn

**Comment by chestozo** [comment]
fixed in 0.0.21
