### ISSUE TITLE
Change mark style

### ISSUE THREAD

**Issue by Quacrom** [chestozo/vscode-bookmarksng#7]
Great job! Simple and effective. Is there any way to change the style or color of the mark?

Greetings

**Comment by chestozo** [comment]
hey @Quacrom !
please upgrade to version 0.0.22
I've added an option to set icon color in there.

**Comment by Quacrom** [comment]
Hi @chestozo 

I love your extension, it is extremely simple and I use it a lot. Many members of our team already use it.

On the change of version 0.0.22 I do not achieve that the update works me.

I have put the color in the right field, both in the work area and in a user:
![imagen](https://user-images.githubusercontent.com/13321249/113523888-e2494980-9578-11eb-8c8e-d669759fc62e.png)

I have restarted vs, but the result is the same:
![imagen](https://user-images.githubusercontent.com/13321249/113523891-eaa18480-9578-11eb-8af0-24f738245039.png)

Is it a problem?

Thanks!

**Comment by chestozo** [comment]
hey )
there was one more version released yesterday 0.0.23
and now when you change the color - it first ask you for confirmation and then should update the color of the icon
please try that one
![image](https://user-images.githubusercontent.com/498934/113546962-b4eeb100-95f5-11eb-8bed-ba34a0c1f010.png)

**Comment by Quacrom** [comment]
Thanks for the reply.

I do indeed I have version 0.0.23:
![imagen](https://user-images.githubusercontent.com/13321249/113607211-f5125b80-9616-11eb-8858-36b24a3566e9.png)

When I change the color (user and work area) it asks me to update:
![imagen](https://user-images.githubusercontent.com/13321249/113607251-fe032d00-9616-11eb-89a3-5278422888bd.png)

But the changes are not reflected:
![imagen](https://user-images.githubusercontent.com/13321249/113607278-05c2d180-9617-11eb-9196-23f142e1ca4d.png)

**Comment by chestozo** [comment]
@Quacrom are you on Windows or on Unix?

**Comment by Quacrom** [comment]
@chestozo Windows 10

**Comment by chestozo** [comment]
thank you!
yep I could reproduce it - doesn't work on windows now
will fix

**Comment by chestozo** [comment]
@Quacrom please update to the 0.0.24
should be fixed now

**Comment by Quacrom** [comment]
@chestozo Now it works correctly.
Are there possibilities to change the icon?

**Comment by Quacrom** [comment]
Another interesting option would be to mark the line:
![imagen](https://user-images.githubusercontent.com/13321249/113625527-09625280-962f-11eb-9194-1fcef3ed71a8.png)
or
![imagen](https://user-images.githubusercontent.com/13321249/113625627-24cd5d80-962f-11eb-8d1c-a71ce261c1a9.png)
